version: "3.8"
name: sage

networks:
  proxy:
    external: true

services:
  sage:
    container_name: sage
    build:
      context: .
      dockerfile: prod.dockerfile
    restart: unless-stopped
    networks:
      - proxy
      - default
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    env_file:
      - .env.prod
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.sage.rule=Host(`sage.${DOMAIN}`)"
      - "traefik.http.routers.sage.entrypoints=websecure"
      - "traefik.http.routers.sage.tls=true"
      - "traefik.http.routers.sage.tls.certresolver=myresolver"
      - "traefik.http.routers.sage.middlewares=auth"
      - "traefik.http.services.sage.loadbalancer.server.port=3000"
